### ISSUE TITLE
[Bug]: plugin does not work for different file types eg. json

### ISSUE THREAD

**Issue by Kerwood** [HiPhish/rainbow-delimiters.nvim#17]
### Neovim version

v0.9.1

### Language affected

JSON/Rust/Bash/Javascript

### Description

I added `HiPhish/rainbow-delimiters.nvim` as a dependency for treesitter without any configuration and it seems to work as intended on Lua files.
But I cant get it to work with JSON, Rust, Bash or Javascript.

**Comment by HiPhish** [comment]
> without any configuration and it seems to work as intended on Lua files.

Yes, the plugin does not need an configuration to work.

> But I cant get it to work with JSON, Rust, Bash or Javascript.

Do you have the Tree-sitter parsers for those languages installed? Without a parser Neovim will not be able to understand the structure of your code. Neovim comes out of the box with a parser for Lua, so that explains why Lua works by default.

**Comment by Kerwood** [comment]
Thank you @HiPhish, I feel like an idiot sandwich :)

![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/4029521/cafdf851-58b8-4a6b-acae-7fb629f0428b)

**Comment by HiPhish** [comment]
Closing this as completed then.
