### ISSUE TITLE
[Bug]: How to turn off the coloring of brackets for useless code?

### ISSUE THREAD

**Issue by littenglt** [HiPhish/rainbow-delimiters.nvim#66]
### Neovim version

v0.9.2

### Language affected

C

### Description

```Text
Some parts of the code are determined by macro definitions whether they work or not. Treesitter will skip the highlighting of these parts of the code, but the brackets will still be colored.
```

**Comment by littenglt** [comment]
for example:
![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/146831861/63fb0ce8-7189-40c1-8a78-ca660b7168e0)

**Comment by HiPhish** [comment]
Ouch, that looks horrible. Here is what is going on: As far as Tree-sitter is concerned that code is just regular C code that gets parsed and highlighted accordingly. Tree-sitter is just a parser, it does not understand that code between `#if 0` and `#endif` will never be compiled. But then the language server (I guess it's clangd) does understand `#if 0` and it tells Neovim to apply different highlighting on top of the current highlighting.

Semantic token highlighting from the language server has a higher priority than Tree-sitter. The problem is that rainbow delimiter highlighting has even higher priority than semantic tokens, so the parentheses "shine through" so to say.

The question becomes, what should I do? Currently the priority is above 200, which is the priority for user highlighting (see `:h vim.highlight.priorities`). I think setting it to 110 (between `treesitter` and `semantic_tokens`) is a good value. What do you think?

**Comment by littenglt** [comment]
Hi HiPhish, thank you for your detailed explanation, but I am not very familiar with this. Could you further tell me how to do it?

**Comment by littenglt** [comment]
Hi HiPhish, 
 I changed the priority of rainbow-delimiters as below, and it works as expected
![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/146831861/ca927943-7864-431b-923f-6346a2988605)

can we support to configure its priority accordingly user's configuration

**Comment by HiPhish** [comment]
> Can we support to configure its priority accordingly user's configuration?

Yes, I will make it configurable per language with a reasonable default value. I think 110 is a good value, it is unlikely that Tree-sitter will override highlighting of delimiters.

**Comment by HiPhish** [comment]
Please try the current `master` branch. I have changed the default priority to 110, which should be a good default value for everyone. You can override it in your settings for all languages (key `''`) and per language:

```vim
" Sets the default to 110, except for Lua where it is 210
let g:rainbow_delimiters = {
   \ 'priority': {
       \ '': 110,
       \ 'lua': 210,
   \ },
\ }
```

**Comment by littenglt** [comment]
Yes, it works well. great thanks.
